# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6', 'Android/Qt6']
  'require':
 add @latest-kf6

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5', 'Android/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kiconthemes': '@stable'
